---
title: "lit review things"
author: "Sylvie"
date: "2025-07-14"
output: html_document
---

```{r}
library(bib2df)
library(stringr)
library(synthesisr)
library(tidyverse)
```

```{r}
process_rayyan<-function(input_bib_file){
  #this function takes a .bib file exported from rayyan (all papers have to have an exclusion decision) and outputs a dataframe 
  
  #read in bib and add columns
  raw_df<-bib2df(input_bib_file)
  df<-raw_df
  df$INCLUSION=NA
  df$EXPORT_DATE=NA
  df$CITED_BY=NA
  df$TAGS=NA
  
  #iterate through each row in dataframe
  for(i in 1:nrow(df)) {
    #split rayyan column into sections
    rayyan_info<-(df$NOTE[i]|>str_split(pattern=" \\| "))[[1]]
    
    #extract inclusion tag 
    inclusion<-(rayyan_info[2]|> str_extract_all(boundary("word")))[[1]][4]
    
    #extract tags from any other rayyan categories
    category<-rayyan_info[-c(1,2)][1]
    tags=c()
    
    for (category in rayyan_info[-c(1,2)]){
      current_tags<-(category|>gsub(pattern=".*: ",replacement="")|>str_split(pattern=","))[[1]]
      tags=c(tags,current_tags)
    }
    
    #extract rayyan metadata
    meta_data<-(rayyan_info[1]|>str_split(pattern = "; "))[[1]]
    export_date<-meta_data[1]|>gsub(pattern = "Export Date: ",replacement="")
    cited_by<-meta_data[2]|>gsub(pattern = "Cited By: ",replacement="")
    
    #add all above extracted info to corresponding columns in df
    df$INCLUSION[i]<-inclusion
    df$EXPORT_DATE[i]<-export_date
    df$CITED_BY[i]<-cited_by
    df$TAGS[i]<-list(tags)
  }
  #return final df
  return(df)
}
```


```{r}
#reading in inital batch of papers screened w/rayyan
scop_26_6_first_pass<-process_rayyan("data/post_first_pass_scopus_26_6_25.bib")
scop_26_6_first_pass
table(scop_26_6_first_pass$INCLUSION)|>barplot()

```
```{r}
scop_included_papers<-scop_26_6_first_pass[(scop_26_6_first_pass$INCLUSION == "Included"),]
df2bib(scop_included_papers,file="data/")
```


```{r}
#create master df that will be updated with every stage of decisions etc
master_db<-scop_26_6_first_pass
```


```{r}
#selecting papers that have been marked as "unclear method" so I can review the method sections in zotero
unclear_method_rows<-(scop_26_6_first_pass|>rowwise()|>summarise(bool= "unclear method" %in% TAGS))$bool
unclear_method_papers<-scop_26_6_first_pass[unclear_method_rows,]
#unclear_method_papers|>df2bib(file="unclear_method_papers.bib")

#after review in zotero, read in separate categories
include_unclear_method<-bib2df("data/unclear_method_papers/decisions/unclear_method_include.bib")
exclude_unclear_method<-bib2df("data/unclear_method_papers/decisions/unclear_method_exclude.bib")
single_fungus_unclear_method<-bib2df("data/unclear_method_papers/decisions/unclear_method_single_fungus.bib")

#change inclusion of these papers in the master database
master_db[(master_db$URL %in% include_unclear_method$URL),]$INCLUSION<-"Included"
master_db[(master_db$URL %in% exclude_unclear_method$URL),]$INCLUSION<-"Excluded"


#add "single fungus" tag
#only has one record so I can cheat (idk how to do this properly)
new_tags<-list(c("unclear method","single fungus"))
master_db[(master_db$URL %in% single_fungus_unclear_method$URL),]$TAGS[1]<-new_tags

```
```{r}
single_fungus_rows<-(master_db|>rowwise()|>summarise(bool= "single fungus" %in% TAGS))$bool
single_fungus_papers<-master_db[single_fungus_rows,]
#single_fungus_papers|>df2bib(file="single_fungus_papers")
single_fungus_papers
```
```{r}
master_db[master_db$INCLUSION=="Included",]$YEAR|>table()|>barplot()

```


web of science search
```{r}
wos_raw<-bib2df("data/wos_24_7.bib",merge_lines = TRUE)
```
```{r}
wos_deduped<-wos_raw
#entries with the same DOI
wos_duplicate_DOI<-(wos_raw$DOI %in% master_db$DOI & !is.na(wos_raw$DOI))
wos_deduped<-wos_deduped[!wos_duplicate_DOI,]
no_doi_master<-master_db[is.na(master_db$DOI),]

#entries w same title
dup<-find_duplicates(c(wos_deduped$TITLE, no_doi_master$TITLE),method="exact",to_lower = TRUE, rm_punctuation = TRUE )
dup_bool<-duplicated(dup,fromLast = TRUE,)
wos_duplicated_titles_bool<-dup_bool[1:(length(wos_deduped$TITLE))]

wos_deduped<-wos_deduped[!wos_duplicated_titles_bool,]
```

```{r}

#df2bib(wos_deduped,file="data/wos_deduped_unsorted.bib")
#write_refs(read_refs("data/wos_deduped_unsorted.bib")[1:20,], format = "ris",file="data/wos_deduped_unsorted_little_bit.ris")
```



